dist: trusty
services:
  - docker
before_script:
  - docker pull drugilsberg/rdkit-ubuntu:latest
  - docker build -f .travis/gene_expression/Dockerfile -t omics_expression .
  - docker build -f .travis/encoded_proteins/Dockerfile -t omics_encoded .
script:
  - docker run -it omics_expression python3 -c "import paccmann_omics"
  - docker run -it omics_expression python3 examples/gene_expression/train_vae.py -h
  - docker run -it omics_encoded python3 -c "import paccmann_omics"
  - docker run -it omics_encoded python3 examples/encoded_proteins/train_protein_encoding_vae.py -h
notifications:
  slack:
    secure: sL/Ls/vS2pT1fj4gV/102JyfhEkJ89SI5+LBahjXvkpHLcO3DVcWDM8fal7IPDm02gq0ielq188XPaj8T9H/GOorlwZTqJuOcaBd7qOkdUO7UpSW+KqAWovyKNOr+xiM9lWGgXNKSeHAn5EQ5KSzbT1QK804jvmwvKT31wmSQ1lvWVNy09P+6R07+GayfhBK1pNkQDHcjqggV4oaEGCigynB/tr04rkP1+7ircSwDR0hg6ObiIwl6AGr1mfkN1ryWp4XKE3IyJ1QQca1wxHjMHvzLIeJX3PsZJayR8EBjd5RAIZjxGodKPpEWExz2S0i8rUEspP5ST/ifJ1Kq+vBnDRPP3cs0OVREo11JLxiv7e03ap4x4p+HAzxf2MQhhTJa0r3a5S9RMCXsGszi3l2lIUpBzmTEL6gQl3o4IezCXE5wD3fIGNf0zpbup7jfawxuLFoa/BWgn2hmT23kmCnCjpwBawQni0POz5WRToFWmVqdfZ2YHEutDuVF+zuWEts/I7tfTCCmDjfRznXlO0wFUkh1GWMCdTSkK5GBxsc4D9V0EWHcCcWTVPowlybuWp2cxmBC+U4Aw+R5v00KndHW8fcY3iQG/cwV5yo3EjNlAPJROnUG6xAobxB+JLD3i/QqREH35scUqzORB1htPNiTq7Y2EDyKF0OJzPeGQo7yxU=
